### ISSUE TITLE
Bug trying to disable cordova telemetry from puppet

### ISSUE THREAD

**Issue by maxence-lefebvre** [mlefebvresopra/docker-forcedroid#1]
```puppet
# Install cordova
package { 'cordova':
  ensure          => 'present',
  install_options => ['--silent'],
  provider        => 'npm',
} -> # Disable telemetry
  exec { 'disable cordova telemetry':
    command => '/usr/bin/cordova telemetry off',
    user    => root
  }
```

```
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns: path.js:7
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:     throw new TypeError('Path must be a string. Received ' + inspect(path));
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:     ^
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns: TypeError: Path must be a string. Received undefined
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:     at assertPath (path.js:7:11)
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:     at Object.join (path.js:1211:7)
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:     at Object.<anonymous> (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:35:31)
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:     at Module._compile (module.js:571:32)
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:     at Object.Module._extensions..js (module.js:580:10)
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:     at Module.load (module.js:488:32)
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:     at tryModuleLoad (module.js:447:12)
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:     at Function.Module._load (module.js:439:3)
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:     at Module.require (module.js:498:17)
==> default: Notice: /Stage[main]/Main/Exec[disable cordova telemetry]/returns:     at require (internal/module.js:20:19)
==> default: Error: /usr/bin/cordova telemetry off returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Main/Exec[disable cordova telemetry]/returns: change from notrun to 0 failed: /usr/bin/cordova telemetry off returned 1 instead of one of [0]
```

**Comment by maxence-lefebvre** [comment]
Note : running following ssh command doesn't return an error

```
vagrant@vagrant-ubuntu-trusty-64:~$ /usr/bin/cordova telemetry off
You have been opted out of telemetry. To change this, run: cordova telemetry on.
```

**Comment by maxence-lefebvre** [comment]
```javascript
if (!global_config_path) {
    var HOME = process.env[(process.platform.slice(0, 3) == 'win') ? 'USERPROFILE' : 'HOME'];
    global_config_path = path.join(HOME, '.cordova');
}
```

HOME environment variable wasn't defined during puppet installation

```puppet
  exec { 'disable cordova telemetry':
    environment => ['HOME=/home/vagrant'],
    command => '/usr/bin/cordova telemetry off'
  }
```
